version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123!
    ports:
      - "1433:1433"
  
  estoque-service:
    build: ./backend/EstoqueService
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EstoqueDb;User=sa;Password=SenhaForte123!
    depends_on:
      - sqlserver
  
  faturamento-service:
    build: ./backend/FaturamentoService
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=FaturamentoDb;User=sa;Password=SenhaForte123!
      - Services__EstoqueService=http://estoque-service
    depends_on:
      - sqlserver
      - estoque-service
  
  frontend:
    build: ./frontend/nota-fiscal-app
    ports:
      - "4200:80"
    depends_on:
      - estoque-service
      - faturamento-service