services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: estoque_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  estoque-service:
    build: ./backend/EstoqueService
    ports:
      - "5189:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=estoque_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy

  faturamento-service:
    build: ./backend/FaturamentoService
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=faturamento_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      EstoqueService__BaseUrl: "http://estoque-service"
    depends_on:
      postgres:
        condition: service_healthy
      estoque-service:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - estoque-service
      - faturamento-service

volumes:
  postgres_data:
